spring.application.name=Apis


spring.datasource.url=jdbc:mysql://195.35.59.3:3306/u484426513_disenocompc226?useSSL=false&serverTimeZone=UTC
spring.datasource.username = u484426513_disenocompc226
spring.datasource.password = S2u4uo#d;70+


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
#Sprint cree tablas

